### ISSUE TITLE
Add a link to the Showroom to the catalog

### ISSUE THREAD

**Issue by mickume** [rhpds/showroom-lb2255-jumpstarter#48]
Add a link to the Showroom to the catalog.yaml entity.

Example
```yaml
links:
    - url: https://devspaces.apps.cluster-msttj.msttj.sandbox4574.opentlc.com/#https://gitlab-gitlab.apps.cluster-msttj.msttj.sandbox4574.opentlc.com/user18/jumpstarter-lab-traton
      title: "DevSpace jumpstarter-lab-traton"
    - url: https://devspaces.apps.cluster-msttj.msttj.sandbox4574.opentlc.com
      title: OpenShift Dev Spaces Workspaces
    - url: https://showroom-showroom-user18.apps.cluster-msttj.msttj.sandbox4574.opentlc.com/
      title: Showroom
```
